create table users (
   id         number generated by default on null as identity,
   first_name varchar2(25) not null,
   last_name  varchar2(25) not null,
   email      varchar2(100) not null,
   pix        varchar2(255) not null,
   phone      varchar2(25) not null,
   crc        varchar2(20) not null,
   created_by varchar2(100),
   created_at date default sysdate,
   updated_at date
);

create or replace trigger trg_users_audit before
   insert or update on users
   for each row
begin
   if inserting then
      :new.created_at := sysdate;
   end if;
   if updating then
      :new.updated_at := sysdate;
   end if;
end;