create table email (
   id           number generated by default on null as identity,
   user_id      number not null,
   send_to      varchar2(255) not null,
   send_from    varchar2(255) not null,
   subject      varchar2(150) not null,
   content_body varchar2(255) not null,
   attachment   varchar2(255) not null,
   created_at   date default sysdate,
   updated_at   date,

   constraint fk_emails_user
   foreign key (user_id)
   references users(id)
   on delete cascade
);
